version: "2"

services:
  jenkins:
    image: giss/jenkins-docker
    container_name: jenkins
    hostname: jenkins
    restart: always
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - /datavol/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
